BEGIN;
CREATE TABLE recebivel (id_recebivel SERIAL PRIMARY KEY, uuid VARCHAR(36) NOT NULL UNIQUE, id_doc INTEGER NOT NULL REFERENCES documento(id_doc), nr_documento VARCHAR(50) NOT NULL, id_cliente INTEGER NOT NULL REFERENCES cliente(id_cliente), id_empresa INTEGER NOT NULL REFERENCES empresa(id_empresa), id_centro_custo INTEGER REFERENCES centro_custo(id_centro_custo), id_plano INTEGER NOT NULL REFERENCES plano_de_contas(id_plano), valor NUMERIC(15,2) NOT NULL, emissao DATE NOT NULL, vencimento DATE NOT NULL, observacao VARCHAR(1000), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE recebivel_parcela (id_parcela SERIAL PRIMARY KEY, uuid VARCHAR(36) NOT NULL UNIQUE, id_recebivel INTEGER NOT NULL REFERENCES recebivel(id_recebivel), numero_parcela INTEGER NOT NULL, vencimento DATE NOT NULL, valor NUMERIC(15,2) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN NOT NULL DEFAULT FALSE, CONSTRAINT uq_recebivel_parcela UNIQUE(id_recebivel, numero_parcela));
CREATE TABLE recebivel_anexo (id_anexo SERIAL PRIMARY KEY, uuid VARCHAR(36) NOT NULL UNIQUE, id_recebivel INTEGER NOT NULL REFERENCES recebivel(id_recebivel), nome_arquivo VARCHAR(255) NOT NULL, caminho_arquivo VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE recebimento (id_recebimento SERIAL PRIMARY KEY, uuid VARCHAR(36) NOT NULL UNIQUE, data DATE NOT NULL, id_conta INTEGER NOT NULL REFERENCES conta(id_conta), id_recebivel INTEGER NOT NULL REFERENCES recebivel(id_recebivel), id_parcela INTEGER REFERENCES recebivel_parcela(id_parcela), valor_recebido NUMERIC(15,2) NOT NULL CHECK (valor_recebido > 0), conciliado BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN NOT NULL DEFAULT FALSE);
CREATE INDEX ix_recebivel_consulta ON recebivel (vencimento, id_empresa, id_cliente) WHERE deleted=FALSE;
CREATE INDEX ix_recebivel_parcela_vencimento ON recebivel_parcela (vencimento) WHERE deleted=FALSE;
CREATE INDEX ix_recebimento_recebivel ON recebimento (id_recebivel) WHERE deleted=FALSE;
COMMIT;
