-- PLA-1221 empresa centro_custo
BEGIN;
CREATE TABLE IF NOT EXISTS empresa (id_empresa SERIAL PRIMARY KEY, uuid VARCHAR(36) NOT NULL UNIQUE, nome VARCHAR(255) NOT NULL, cnpj VARCHAR(20), tipo_empresa VARCHAR(20) NOT NULL DEFAULT 'EMPRESA', codigo_externo VARCHAR(50), ativa BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN NOT NULL DEFAULT FALSE, CONSTRAINT ck_empresa_tipo CHECK (tipo_empresa IN ('EMPRESA', 'SPE', 'SCP')));
CREATE TABLE IF NOT EXISTS centro_custo (id_centro_custo SERIAL PRIMARY KEY, uuid VARCHAR(36) NOT NULL UNIQUE, id_empresa INTEGER NOT NULL REFERENCES empresa(id_empresa), codigo VARCHAR(50) NOT NULL, nome VARCHAR(255) NOT NULL, codigo_externo VARCHAR(50), ativo BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN NOT NULL DEFAULT FALSE);
ALTER TABLE conta ADD COLUMN IF NOT EXISTS id_empresa INTEGER REFERENCES empresa(id_empresa), ADD COLUMN IF NOT EXISTS id_centro_custo INTEGER REFERENCES centro_custo(id_centro_custo);
ALTER TABLE titulo ADD COLUMN IF NOT EXISTS id_empresa INTEGER REFERENCES empresa(id_empresa), ADD COLUMN IF NOT EXISTS id_centro_custo INTEGER REFERENCES centro_custo(id_centro_custo);
ALTER TABLE movimentacao_conta ADD COLUMN IF NOT EXISTS id_empresa INTEGER REFERENCES empresa(id_empresa), ADD COLUMN IF NOT EXISTS id_centro_custo INTEGER REFERENCES centro_custo(id_centro_custo);
COMMIT;
